apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - rbac.yaml
  - vmselect-federated.yaml
  - vmalert.yaml
  - vmagent-catchall-service.yaml
  - vmnodescrape-kubelet.yaml
  - httproute.yaml
