apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: "zone-b-"

resources:
  - ../../base

patches:
  - target:
      kind: VMAgent
      name: vmagent
    patch: |
      - op: replace
        path: /spec/nodeSelector/topology.kubernetes.io~1zone
        value: eu-west-1b
      - op: replace
        path: /spec/externalLabels/availability_zone
        value: eu-west-1b
      - op: replace
        path: /spec/extraEnvs/4/value
        value: ''
      - op: replace
        path: /spec/remoteWrite/0/url
        value: http://vminsert-vm-eu-west-1b-vmcluster.monitoring.svc.cluster.local:8480/insert/0/prometheus/api/v1/write
